name: focusnotes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  provider: ^6.1.5+1
  firebase_auth: ^6.0.2
  uuid: ^4.5.1
  either_dart: ^1.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  sign_in_with_apple: ^7.0.1
  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
